### ISSUE TITLE
Prefill text message?

### ISSUE THREAD

**Issue by KyleAMathews** [anarchicknight/react-native-communications#1]
That'd be very useful for a project I'm thinking of doing :)

**Comment by anarchicknight** [comment]
I would have loved to do this but unfortunately Apple does not allow including any message text with the "sms:" URL scheme

https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/SMSLinks/SMSLinks.html

**Comment by KyleAMathews** [comment]
It looks like it's possible according to this stackoverflow answer http://stackoverflow.com/questions/10848/how-to-programmatically-send-sms-on-the-iphone

**Comment by anarchicknight** [comment]
Just had a read through that thread.

The posters in there confirm it is not possible using the "sms:" URL scheme which is what this package is designed to make use of (launching the system built in apps for phone, email, message).

You can do it using MFMessageComposeViewController - this uses a view controller launched inside the current app. This will be possible to do in React Native using RCTViewManager but that would be a whole new component and should not be covered here.

Thinking about it, if no one else beats me to it then I may look at creating this in the next week or so.

Going to close this issue.

**Comment by KyleAMathews** [comment]
That'd be great!

**Comment by anarchicknight** [comment]
Currently working on it - will give you a nudge when its published

**Comment by anarchicknight** [comment]
published - https://github.com/anarchicknight/react-native-message-composer

**Comment by KyleAMathews** [comment]
awesome, thanks! It'll be a little while before I jump into my ios project but looking forward to using this.
