### ISSUE TITLE
URL encode issue

### ISSUE THREAD

**Issue by melihmucuk** [anarchicknight/react-native-communications#11]
Hi, email function should uses url encode string. Forexample If I send email with string contains '&' char, it doesn't show after special char.

**Comment by anarchicknight** [comment]
The argument could go both ways with this i.e. you could say it is the responsibility of the library to do this, or you could say it is up to the developer to sanitise the string before passing it to the email method.

I will leave this open though as an enhancement which I will look at adding if I have the time

**Comment by anarchicknight** [comment]
this has now been available for a while
