### ISSUE TITLE
Application restart after call ends

### ISSUE THREAD

**Issue by tuanhm93** [anarchicknight/react-native-communications#15]
Hi. I have a problem when i make a call from my app and then i turn back to my app it restart :(
Is any way to don't let application restart when call ends? please help me. Sorry my english is bad :(

**Comment by anarchicknight** [comment]
Thanks for the report.

Do you have some sample code which replicates the issue? When you say the app restarts, what exactly do you mean? Does the app close and then reopen, or is it something more along the lines of components being re-rendered with unexpected state?

**Comment by anarchicknight** [comment]
@tuanhm93 did you have any further feedback on this issue for me to try and replicate?

**Comment by tuanhm93** [comment]
Ok,i will explain detail of this for you later, sorry for that.

**Comment by anarchicknight** [comment]
closing this for now - if you can replicate and provide some steps to help debug then feel free to reopen
