### ISSUE TITLE
This doesn't work, FYI

### ISSUE THREAD

**Issue by bradynapier** [anarchicknight/react-native-communications#2]
I am pretty sure this doesn't work, I tried installing it but it doesn't do anything when I press the button.

**Comment by bradynapier** [comment]
Can't handle url: sms:0123456789

**Comment by bradynapier** [comment]
Can't handle url: telprompt:0123456789

**Comment by bradynapier** [comment]
Can't handle url: tel:0123456789

**Comment by anarchicknight** [comment]
was this with a brand new project?

At present, if I init a brand new project using react-native 0.11.4 I cannot even launch the app on simulator using the default template

**Comment by anarchicknight** [comment]
I have been able to replicate the issue running on react-native 0.11.2.

I am looking in to the issue

**Comment by bradynapier** [comment]
Thanks!

**Comment by anarchicknight** [comment]
My bad - I did not provide enough info in the project readme.

This will only work when running on an actual device as the simulator does not have the required telephony/messaging bits installed.

I have just tested on an actual device and it still works for me. Are you able to confirm running on an actual device too?

I will update the readme file now.

Cheers

**Comment by bradynapier** [comment]
Yeah I figure that might be the case, I am not running on a device at this time but for now I will assume it will!  Thanks!

**Comment by anarchicknight** [comment]
cool. Will close issue. If you have any issues when running on a device feel free to get in touch
