### ISSUE TITLE
Ability To Pre Fill Text Messages

### ISSUE THREAD

**Issue by jakesorce** [anarchicknight/react-native-communications#21]
I've seen a few apps with this ability. It would be great if that functionality could be added to this. If it's possible, get me going in the right direction and I can make a pull request as well. Thanks

**Comment by jakesorce** [comment]
fixed by: https://github.com/anarchicknight/react-native-communications/pull/22

**Comment by anarchicknight** [comment]
Thanks for this.

I'm currently on holiday in Spain but will take a look when I get back in just over a week

**Comment by jmeyers44** [comment]
really helpful @jakesorce. @anarchicknight can we still expect this to get merged in soon based on your last comment?

**Comment by anarchicknight** [comment]
Yes, I'm travelling today but it should get done within the next 2 days

**Comment by anarchicknight** [comment]
This has now been manually merged in - had to make some changes to support Android and also updated README and bumped package version
