### ISSUE TITLE
Communcations.text not working with two arguments

### ISSUE THREAD

**Issue by ospfranco** [anarchicknight/react-native-communications#23]
Using react-native 0.29.0, email works just fine but when I do

`Communications.text('123123123', 'random text')`

does not work, calling:

`Communcations.text('123123123') works fine`

console shows:

`you supplied too many arguments. You can either supply 0 or 1`

**Comment by anarchicknight** [comment]
Is this using 2.1.0 of the library which was pushed earlier today?

Is it a problem for iOS and Android? If so which versions?

I tested on both platforms earlier (iOS 9, Android 5.1) and it worked OK (RN version was the latest though not 0.29 so that could be a factor)

**Comment by ospfranco** [comment]
My bad, did not realize 2.1.0 was pushed today, I installed it yesterday but only got to using text today. thanks!

**Comment by anarchicknight** [comment]
No worries :)
