### ISSUE TITLE
How to dynamically insert a number or part of body message?

### ISSUE THREAD

**Issue by jaygarg** [anarchicknight/react-native-communications#27]
How do you use a variable in place of the number or part of the message of the body so that I could dynamically insert it based on who I want to text?

What's the correct syntax for writing in a variable?

**Comment by anarchicknight** [comment]
Are you still stuck on this?

An example from one of my current projects is shown below. You can just put the dynamic values you want using normal string concatenation etc

onPress={() => Communications.email(
              ['anarchicknight@gmail.com'],
              null,
              null,
              'Feedback for App',
              '\n\n' +
              'Platform: ' + Platform.OS + '\n'
              + 'Device: ' + DeviceInfo.getModel() + '\n'
              + 'Software Version: ' + DeviceInfo.getSystemVersion() + '\n'
              + 'App Version: ' + DeviceInfo.getVersion() 
            )}

Does that help at all?

**Comment by jaygarg** [comment]
Thanks for the help!
