### ISSUE TITLE
Methods only accessible from Communications.deafult, not Communications when using old styled import

### ISSUE THREAD

**Issue by JakeRuth** [anarchicknight/react-native-communications#28]
Edit: Quick answer -> using an old styled import `require('...') can cause this behavior.`

I just installed this plugin, I am using version 2.1.0

I am running this on the IOS simulator with React Native 0.28.0, the docs say to just call:
`Communications.web(...`

but in order for it to work, I need to call it this way (discovered this through debugging):
`Communications.default.web(...`

I believe this was introduced in this commit https://github.com/anarchicknight/react-native-communications/commit/460c7d8dc2123d0efaedd90a58ced0e6f705cff9
when the last line of `AKCommunications.js ` was changed from `module.exports = communication;` to `export default communication;`

I'm not great with es6 yet, so the above is an educated guess.  This isn't a big issue, but I think it should either be changed back to match the documentation, or update the documentation.

Hopefully this helps, I'll try to respond as promptly as possible but I am a very busy person (aren't we all?)
p.s. If I end up being right that that's the issue, I can make a PR to get my hands in this repo.  Thanks for open sourcing it!

**Comment by anarchicknight** [comment]
Thanks for the report.

Im using 2.1.0 in a project at the moment and am able to use it as the docs say, so a bit stumped at the moment (using react native 0.30.0 but that should not make a difference).

How are you requiring the module? e.g. import Communications from 'react-native-communications'

Are you able to provide the file where you are seeing the issue (if it is not confidential at moment) or possibly a slightly more expanded section of the code than above?

Willing to take input from any other users to see if they are having the same issue

**Comment by JakeRuth** [comment]
Hm that is strange.  I was importing it using older style: `var Communications = require('react-native-communications');`

I did end up however switching to this plugin https://www.npmjs.com/package/react-native-message-composer since I needed support to send a text with multiple recipients.  If it doesn't get reproduced by yourself importing it using the snipplet I posted above I will test locally and send larger snipplets and information from the debug console describing the `Communications` variable

**Comment by anarchicknight** [comment]
Ah, that may be it. Im not sure whether mixing the older non es6 requires with es6 code is supported or not.

The documentation shows using es6 imports in the usage example.

When I get a bit of time I will see if I can replicate with the older style import, I will also read up on whether you can mix and match require format with es6 code etc

Hope my other module is working out for you :)

**Comment by JakeRuth** [comment]
Ah okay.  And that's a good callout so my title here isn't that correct.  This seems more like a me issue of mixing syntax styles.  I'll update this ticket, seems to me like it may not be a bug at all, but I do predict other people will run into it.

**Comment by anarchicknight** [comment]
cheers.

I definitely want to read up on the mixing of the old and new style though and find out if there are ways around it etc, and if not will update the docs to emphasise using the new style import

**Comment by anarchicknight** [comment]
I have made some changes to how the Communications object and individual methods are exported.

It seems to work for me now when using old & new styles

e.g.
var Communications = require('react-native-communications')
or
import Communications from 'react-native-communications'

will now both work when calling Communications.web('http://www.github.com') etc

The ability to import single methods will also be available

e.g. import { web } from 'react-native-communications' which can be called just as web('http://www.github.com')

The updated version should be committed in the next couple of days.
