### ISSUE TITLE
Error on cancelling on android

### ISSUE THREAD

**Issue by lavokad** [anarchicknight/react-native-communications#29]
Hi, once email, phone or web bottom prompt appears (to choose the app actions should be completed) and one presses somewhere on the screen, an error is thrown:
`undefined is not a function(evaluating 'handler(appStateData.app_state)')`
Has someone seen this too?

Thanks

**Comment by anarchicknight** [comment]
will look in to this when I get a chance over the next week or so, unless someone gets a chance before then and can submit a PR

**Comment by anarchicknight** [comment]
Do you have any more info on this, just tried debugging now and I don't get the error. I can tap on screen to close the intent chooser and the app is still running with no issues.

What version of Android are you on, what device, React Native version etc?

Do you have sample code which will exhibit the issue?

**Comment by lavokad** [comment]
Hi, thanks. I figured out that the issue was caused by code. Sorry for
confusion.

**Comment by lavokad** [comment]
*other code I meant

**Comment by anarchicknight** [comment]
no worries - thanks for letting me know
