### ISSUE TITLE
com.apple.MobileSMS.CKRecipientAvailabilityTimeout

### ISSUE THREAD

**Issue by jaygarg** [anarchicknight/react-native-communications#30]
Sending an SMS was working just fine before I downloaded Xcode 8 and am running on the simulator on iOS 10. Now it will open up an SMS message just fine with the body populated, but the number won't auto-populate properly - it will say "No Name" instead and have a spinner next to it and then throw an error com.apple.MobileSMS.CKRecipientAvailabilityTimeout.

Any help on this would be appreciated!

**Comment by anarchicknight** [comment]
will look in to this when I get a chance over the next week or so, unless someone gets a chance before then and can submit a PR

**Comment by anarchicknight** [comment]
Looks like this is a simulator only error. I could replicate on the simulator but once run on a real device running iOS10 it worked with no problems.

Are you able to check on a real device?

**Comment by jaygarg** [comment]
Ah ya, it works on a real device - weird! Thank you again for your help!

**Comment by dsernst** [comment]
I'm also seeing this in the simulator. Haven't tried on device yet.

**Comment by anarchicknight** [comment]
Yeah the simulator does not seem to support it fully, but real devices seem to work no problem
