### ISSUE TITLE
This app is not allowed to query for scheme mailto

### ISSUE THREAD

**Issue by dcurletti** [anarchicknight/react-native-communications#33]
<Warning>: -canOpenURL: failed for URL: "mailto:test%40email.com?" - error: "This app is not allowed to query for scheme mailto"
<Notice>: Can't handle url: mailto:test%40email.com?

I'm getting these errors using xcode 8 and developing for ios10.

**Comment by anarchicknight** [comment]
Is this on the simulator? Majority of the methods won't work on the simulator as they don't have the requiredsystem apps present. This is mentioned in the readme. If not in the simulator let me know and I will investigate shortly

**Comment by dcurletti** [comment]
Okay, cool.  let me check.

**Comment by dcurletti** [comment]
Confirmed working on native device, not in simulator.  Sorry for not seeing that in the Readme.  Thanks for the quick help!

**Comment by anarchicknight** [comment]
No worries :)

**Comment by sohaib-grayphite** [comment]
i am facing the same issue but on Samsung real device.On other android devices, it is working fine.
