### ISSUE TITLE
Success/error callback?

### ISSUE THREAD

**Issue by dwilt** [anarchicknight/react-native-communications#36]
It would be super handy and useful to know if a text or email was actually sent or failed to send for analytics purposes.

**Comment by anarchicknight** [comment]
Unfortunately this is not supported by the react native Linking package as far as I am aware (which this library uses). There is a callback but that is only for if the linker fails to open the URL.

It's a shame as has been asked for a few times (#4, #10) but there is nothing we can do about it

**Comment by dwilt** [comment]
How are they doing it here https://www.npmjs.com/package/react-native-sms#example

**Comment by anarchicknight** [comment]
They are wrapping native platform components - in fact their ios code implementation looks similar to one of my other modules here https://github.com/anarchicknight/react-native-message-composer

This module is designed as a lightweight wrapper for the Linking component in react native and so it won't wrap any native platform code

**Comment by smitthakkar1** [comment]
@anarchicknight  Any update since then ?
@dwilt I am in the same boat. By any chance, do you remember which solution did you applied ?

**Comment by dwilt** [comment]
@smitthakkar1 I don't remember, sorry.
