### ISSUE TITLE
Encoded email address

### ISSUE THREAD

**Issue by leonskim** [anarchicknight/react-native-communications#37]
Hi, 

I'm trying to send an email but `Communications.email()` doesn't work since `@` is escaped to `%40` by `encodeURIComponent()` on [this line](https://github.com/anarchicknight/react-native-communications/blob/master/AKCommunications.js#L61) which can't go through `Linking.canOpenURL()`. For example,

`Communications.email(['test@test.com'], null, null, null, null)`

Could you check it out? Thanks in advance.

**Comment by anarchicknight** [comment]
Is this on ios, android or both? And is it running on device or emulator?

**Comment by leonskim** [comment]
@anarchicknight I have it tested on both devices and emulators but I don't think it would matter since escaped %40 is passed.
```
Can't handle url: mailto:test%40test.com?
```

**Comment by anarchicknight** [comment]
Ok thanks, will take a look tomorrow after work

**Comment by leonskim** [comment]
@anarchicknight My understanding about `Linking` was wrong. It does handle escaped strings so I tried again and it worked. I had a glitch on the other part of the app messing up my email settings. Solved!
