### ISSUE TITLE
wrong email selected when having multiple accounts [android]

### ISSUE THREAD

**Issue by lognad** [anarchicknight/react-native-communications#38]
when having a multiple accounts, using email method, it selects the previously selected mail account(in gmail. however haven't tested in others, but case may be similar for others too) instead of the one being used by the application for log in.

i'm using google signin for authentication.

hence would be great if correct email account is/can be selected, in case of multiple accounts rather than correcting it afterwards in the google mail

**Comment by anarchicknight** [comment]
Hi,

From what I have read about the Android Intent system, which is what the react native Linking module uses (which in turn this module uses) it is not possible to specify a certain email account to use when launching the mail client.

Will close this for now but if anyone finds any info to the contrary then I will happily take another look
