### ISSUE TITLE
Return to app after email sent

### ISSUE THREAD

**Issue by etaymor** [anarchicknight/react-native-communications#4]
This is working great! Is there any way to return to the app if the user hits cancel or send as opposed to staying in the Mail app?

**Comment by anarchicknight** [comment]
Hi,

As far as I am aware I don't think it is possible. I will do a bit of research over the weekend though to double check

**Comment by anarchicknight** [comment]
It does not look like this is possible with the openurl approach that this library uses.

I do have https://github.com/anarchicknight/react-native-message-composer available which should do what you require
