### ISSUE TITLE
Programmatically send text

### ISSUE THREAD

**Issue by tc0087** [anarchicknight/react-native-communications#40]
How can I programmatically send a text using this package? It only pre-fills a text-message right now. I still need to click "Send" to actually fire the text.

**Comment by anarchicknight** [comment]
This is not possible with this library and won't become a supported workflow sorry.

It is technically possible on Android (but requires extra permissions being granted through the manifest etc) but is not possible on iOS without using an external service to send the sms (so not the users phone number).
