### ISSUE TITLE
Send an e-mail automatically

### ISSUE THREAD

**Issue by ArwaLh** [anarchicknight/react-native-communications#41]
I would like to thank you for this project ,it has many interesting feature that I have tested myself.
I only have a question about how to automate the sending of an e-mail. In fact,I want to send an e-mail to the application users without opening the current e-mail apps on the device.
Thank you.

**Comment by anarchicknight** [comment]
Hi,

Thanks for the question.

This library is a convenience wrapper around the [Linking](https://facebook.github.io/react-native/docs/linking.html) module in react-native. The whole purpose of it is to launch an email client for the email method.

You could probably write a native module which will allow sending emails programatically but this module does not have that as one of its supported use cases and will not in the future either sorry.

Thanks

**Comment by ArwaLh** [comment]
Hi,

Thank you for answering my question. I will try to write a native module myself. 
I will let you know about the result.

Thanks
