### ISSUE TITLE
Back to app from text

### ISSUE THREAD

**Issue by priyesh9875** [anarchicknight/react-native-communications#42]
After calling `text` method, then when back button is pressed it doesn't return to app. Instead it goes to home screen.

Works good in `phonecall` case.

Platform: Nexus 6 Android 6

**Comment by anarchicknight** [comment]
Hi,

Thanks for the report.

Can you try performing the same action by using the built in Linking library from Facebook in react-native?

This library is a convenience wrapper around the Linking module, so if the same thing happens using Linking directly then there will be nothing that I can do about it in this library.

Thanks

**Comment by priyesh9875** [comment]
Just tried calling Linking Url `sms:number?body=yourMessage`, same result. Looks like its a problem in react-native or android.
 
Is it working as expected in IOS?

**Comment by kamrankamrani** [comment]
any progress?
