### ISSUE TITLE
prompt of phonecall doesn't work

### ISSUE THREAD

**Issue by jiangsumadai** [anarchicknight/react-native-communications#46]
"react": "15.3.2",
    "react-native": "0.34.1",

no matter if promot is true or false, the system always shows promot.

phone version:  10.2

**Comment by anarchicknight** [comment]
I have just tested on iPhone 6 iOS 10.2.

It is working as expected for me on RN 0.34.1 and 0.40.0 - can you show me the code you are using?

**Comment by jiangsumadai** [comment]
import Communications from 'react-native-communications';
...
Communications.phonecall('12345', false)

@anarchicknight

**Comment by anarchicknight** [comment]
what version of the library are you on? I am unable to replicate your issue unfortunately

**Comment by jiangsumadai** [comment]
v2.2.1 @anarchicknight

**Comment by anarchicknight** [comment]
are you able to take a recording showing the issue? and the exact full code from the file which is causing it?

Im not able to replicate this at all - and there have been no reports from other users experiencing the issue either

**Comment by jiangsumadai** [comment]
@anarchicknight which version of api are you using?
I think the api of 10.2 doesn't support call directly, I tryed with the following code just now, but the system showed the dialog.
[[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"tel://10086"]];

**Comment by anarchicknight** [comment]
My library doesn't call native code directly. It uses the Linking module from react native so it will be using whatever react native uses via that module.

However I have tested on a device running 10.2 and using the same versions of the library and react native as you and can't replicate so it suggests something else strange is going on.

I will try and dig in to the implementation of the Linking module in the react native codebase and see if there is anything in there which suggests why it may be happening

**Comment by jiangsumadai** [comment]
thank you, waiting for your response

**Comment by anarchicknight** [comment]
Can't find anything to suggest why you are seeing this issue.

I can't replicate with any of my code examples, can you provide a small sample project where you can replicate the issue so I can try running that up?

**Comment by jiangsumadai** [comment]
thanks for your kind response, following is my demo and two screen shots
[CommunicationsDemo.zip](https://github.com/anarchicknight/react-native-communications/files/754040/CommunicationsDemo.zip)
![img_3108](https://cloud.githubusercontent.com/assets/8002482/22640004/c2370dca-ec8b-11e6-9377-271c4076d0e3.PNG)
![img_3106](https://cloud.githubusercontent.com/assets/8002482/22640024/cefedac4-ec8b-11e6-83c7-afa04af2d89f.PNG)
![img_3107](https://cloud.githubusercontent.com/assets/8002482/22640025/cf002e9c-ec8b-11e6-826d-df43f164715f.PNG)

**Comment by jiangsumadai** [comment]
@anarchicknight thanks for your kind response, following is my demo and three screen shots.
before running, you should 'npm install'

[CommunicationsDemo.zip](https://github.com/anarchicknight/react-native-communications/files/754130/CommunicationsDemo.zip)
![img_3112](https://cloud.githubusercontent.com/assets/8002482/22641324/3a8db846-ec91-11e6-8aa9-553d4d97a934.PNG)
![img_3113](https://cloud.githubusercontent.com/assets/8002482/22641325/3a8ec646-ec91-11e6-9aa2-df682826f169.PNG)
![img_3114](https://cloud.githubusercontent.com/assets/8002482/22641323/3a8d186e-ec91-11e6-9ca8-e865fb552703.PNG)

**Comment by anarchicknight** [comment]
I have just run up your demo on an iPhone 6 running 10.2.

Everything worked as expected, 123 caused the prompt to show. 456 went straight to dialling the number.

Are you still getting this issue? What language is your device set to? Its a long shot but I can't think of anything else which could be causing this for your device only

**Comment by wandersage** [comment]
@anarchicknight , Hi. 
I have the same problem. I'm using v2.2.1 too. I test my app on iOs simulator with 
`<TouchableOpacity onPress={()=> Communications.phonecall('380661231213',true)} />`
and receive this messages on log after click - 

> <Warning>: -canOpenURL: failed for URL: "telprompt:380661231213" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
> <Notice>: Can't handle url: telprompt:380661231213

The same result with using false. 
On Android it works fine.
I think that it  doesn't work because iOs simulator hasn't the caller app.

**Comment by anarchicknight** [comment]
Yes it won't work on the simulator, only on a device for iOS. My understanding was that the original poster was having an issue on an actual device though (which i can not replicate)

**Comment by mac-elumen** [comment]
Wow, that was my problem @anarchicknight. I should read deeper next time the README.

**Comment by pvsousalima** [comment]
I can say I am having the same issue. 

```
  "react": "15.4.2",
    "react-native": "0.41.2",
    "react-native-communications": "^2.2.1",
```

**Comment by anarchicknight** [comment]
Do you mean you have the issue on a real device too? If you are on the simulator it will not work. If you have issues on a real device can you please provide a small example project which demonstrates the issue as I cannot replicate on a real device

**Comment by pvsousalima** [comment]
It's in the real device, after compiling with the release option, it's not in the simulator. I am using 

```
() => Communications.phonecall(this.state.numberToCall, false)
```

But yet I do get the prompt showing and asking for confirmation to call.

**Comment by pvsousalima** [comment]
I bet you'll need an app developer account since releasing it adds the developer signature profile to the app making it available for releasing or publishing!

**Comment by anarchicknight** [comment]
Damn - if thats the case I won't be able to test. I will give it a go though and see if I can build in release.

Out of interest, does it work OK for you if you build in debug/dev mode and install on phone?

**Comment by drewvolz** [comment]
This is a "note/known issue" with openURL in iOS 10.3

> When a third party application invokes openURL: on a tel:/ facetime-audio:/, or facetime-audio:/
iOS displays a prompt and requires user confirmation before dialing.

**Comment by anarchicknight** [comment]
Thanks for the info.

For the people experiencing this issue can I also ask that you check if the issue happens just using the Linking library directly from react-native? If it does then nothing can be done for this library as it is just a wrapper on top of Linking from RN

**Comment by kam187** [comment]
It's a new 'feature' in ios 10.3 :/ .openurl witl tel: now shows a prompt which you can't remove.

**Comment by anarchicknight** [comment]
Closing this issue due to age and info provided above
