### ISSUE TITLE
Communications.text('0123456789') show Android wrong

### ISSUE THREAD

**Issue by 2ducanhpham** [anarchicknight/react-native-communications#47]
Send messenger on Android 'Nexus 5 - 6.0.1' show 123456789 instead 0123456789. Do not send messenger

**Comment by anarchicknight** [comment]
What version of RN and what version of this library? It is not an issue I have seen before so trying to narrow down exact versions so I can try and replicate

**Comment by 2ducanhpham** [comment]
I use React native v0.37, react": "15.3.2"

**Comment by anarchicknight** [comment]
Thanks. And what version of this library are you using?

Do you have a small sample project which demonstrates the issue that I can checkout and try to replicate?

**Comment by anarchicknight** [comment]
Are you still getting this issue? Do you have any sample code I can use to to replicate the issue?

I don't seem to be able to replicate it myself running on an actual device on 7.0 or on emulator running 6.0

**Comment by 2ducanhpham** [comment]
I have 2 android devices naxus, os 5 & os 6. Only OS 6 has this error

**Comment by anarchicknight** [comment]
Have you got some sample code which will replicate the issue? So far I have been unable to replicate when running on an emulator. The only physical device I have to test on is on 7.0

**Comment by 2ducanhpham** [comment]
I followed your instructions. I have tried again with many other devices but I do not know why one device is faulty

**Comment by anarchicknight** [comment]
Do you have a small sample project you can provide which will replicate the issue please?

**Comment by 2ducanhpham** [comment]
my code : 
Communications.text(phone = "0123456789"); 
devices: IP6s, Ip7, ip5s is OK

**Comment by anarchicknight** [comment]
Are you putting phone = within the method call? You should just put the phone number as a string

e.g. Communications.text("0123456789")

Can I also ask that you check if the issue happens just using the Linking library directly from react-native? If it does then nothing can be done for this library as it is just a wrapper on top of Linking from RN

**Comment by anarchicknight** [comment]
@2ducanhpham Did you find out if the same issue also happens using the Linking library from React Native?

**Comment by 2ducanhpham** [comment]
It only happens at one device.
