### ISSUE TITLE
Is it possible to get delivery report for SMS? 

### ISSUE THREAD

**Issue by moostad** [anarchicknight/react-native-communications#5]
I'm just wonder is it possible to get delivery report, get incoming sms and read or delete it? 
I mean can I write an alternative message app for IOS and Android with react native?

**Comment by ucnc** [comment]
I just read an article about it and looks like there is no way to do something like this in IOS (due to apple  privacy concerns) however I'm not sure about Android .

**Comment by anarchicknight** [comment]
As you have found out yourself it is not possible to intercept incoming sms on iOS.

This is possible on Android, but varies depending on software version. There is some useful info on the [Android Developers Blog](http://android-developers.blogspot.fi/2013/10/getting-your-sms-apps-ready-for-kitkat.html) related to this.

I am going to close this issue now as it is not something I will be looking to support in this module
