### ISSUE TITLE
Unsoported action 

### ISSUE THREAD

**Issue by peter1a** [anarchicknight/react-native-communications#50]
Have problem with using "email", getting error on Android - Unsuported action(That action is not currently supported.)

Also error on iOS error: "This app is not allowed to query for scheme mailto"

react 15.4.2
react-native 0.41.2

**Comment by peter1a** [comment]
Sorry, works only on real device :)

**Comment by t1k3hu** [comment]
Unsupported action
This action is not currently supported.

(For the search.)
