### ISSUE TITLE
Keep App In StatusBar on .text(phone, body) for iOS

### ISSUE THREAD

**Issue by JohnAntonusMaximus** [anarchicknight/react-native-communications#51]
Hey great repo! Quick question...is there any way to tab the app in the status bar for iOS when the .text(phone, body) method is called? From what I see right now, on iOS when phonecall() method is called, it enters the phone app and when the calls ends, it returns automatically back to the app, but with the text() method, it goes to the messaging app for iOS, but you need to exit out of the messaging app and navigate back to the app from the home screen to get back to where you were. 

Is there any way to keep the app in the status bar to return to after text messaging? 

Android has the benefit of the back button, so this really isn't a problem there, just on the text() method for iOS.

**Comment by anarchicknight** [comment]
Thanks for the question.

This library is a wrapper on top of the Linking library in React Native, so it can only do what that does with regards to how it handles links once opened.

Can you give it a check using Linking, and if that does do what you wish let me know and I will investigate to see why it does not happen with this library

**Comment by anarchicknight** [comment]
@JohnAntonusMaximus Did you find out whether the same thing happened via the Linking library from React Native?

**Comment by JohnAntonusMaximus** [comment]
No, read through the documentation and there's no mention of it 🤷🏻‍♂️

**Comment by anarchicknight** [comment]
OK thanks for the response - it's what I thought as I don't do anything funky to mess with how Linking works from React Native.

I will close this as nothing can be done for this module.

It may be possible to do what you want with a native bridged module - I have no idea if such a module already exists though sorry
