### ISSUE TITLE
Use phone number from api

### ISSUE THREAD

**Issue by itswaze** [anarchicknight/react-native-communications#52]
I have an app, which fetchs the clients contacts from a web service. And I have a button to call that client, but instead of having to write their phone number directly to the code, I want to be able to just call the method that I saved earlier, so everytime any client changes the number, I don't have to manually change in the app.

Something like this: onPress: () => Communications.phonecall({this.state.tel}, true)

Is this possible?

**Comment by anarchicknight** [comment]
Have you given this a try? It should be easily possible - all the method does is take in a string for the phone number and how you want to compose that string is entirely up to you. Pulling it from state should be simple enough.

If you can't get it to work give me a shout with some example code and I will take a look

**Comment by itswaze** [comment]
@anarchicknight Thanks for the response! I was trying:

`onPress: () => Communications.phonecall({this.state.tel}, true)`

But I couldn't get it to work, it was giving me an Unexpected token error, don't know why.
My code is this: 

```
        <Navbar
          bgColor={"#1f1f1f"}
          statusBar={{
              style: "light-content",
          }}
          image={{
              source: require('../images/icon.png'),
              resizeMode: 'cover',
              style: {width: 35, height: 25}
          }}
          right={{
            label: "LIGAR ",
            icon: "ios-call-outline",
            iconColor: "#f48529",
            style:{color: "#f48529", fontSize: 13, fontFamily: 'rubik-regular'},
            onPress: () => Communications.phonecall('+351000000000', true)
          }}
        />
```

and the telephone number comes from:

```
  componentWillMount(){
    contactsAPI.getClientContacts().then((res) =>{
      this.setState({
        tel: res.Telefone
      })
    });
  }
```
