### ISSUE TITLE
Communication.text() on iOS times out

### ISSUE THREAD

**Issue by kennetpostigo** [anarchicknight/react-native-communications#58]
When calling the text function it opens up iMessage and can't find the "name" but I think referring to the phone number. Instead just says `No Name` in red text and has alert dialog saying it timed out.

This is on React-Native v0.43.0

![screen shot 2017-06-19 at 8 21 41 pm](https://user-images.githubusercontent.com/8888991/27311160-1c43e3a6-552d-11e7-9016-6e818e76b1f1.png)
I'm calling it in the following manner:
```js
import { text } from 'react-native-communications';
class MyComponent extends Component{
  ...
  sendText = (phone, body) {
     text(phone, body);
  }
}
```

**Comment by anarchicknight** [comment]
This happens when running in the emulator as the emulator does not have all the required components.

Closing this issue - feel free to reopen it if you can replicate on a real device
