### ISSUE TITLE
Communications.text("1111111111", "hello") doesn't prefil the message on Android

### ISSUE THREAD

**Issue by ghost** [anarchicknight/react-native-communications#61]
Communications.text("1111111111", "hello") doesn't prefil the message on Android

**Comment by anarchicknight** [comment]
Have you got any further information such as module version, RN version, devices tested on etc?

Can you please try the same using the built in Linking library that react native provides and see if it replicates using that? This library is just a wrapper on top of that and if it also happens using Linking then I cannot do anything about it.

**Comment by anarchicknight** [comment]
@ghost Any feedback on this?

**Comment by anarchicknight** [comment]
Closing due to age and no further feedback
