### ISSUE TITLE
Settings?

### ISSUE THREAD

**Issue by bfarrgaynor** [anarchicknight/react-native-communications#62]
Whenever I try to call the methods I seem to be blocked by iOS? 

Eg:
URL: "mailto:?subject=&body=" - error: "This app is not allowed to query for scheme mailto"

**Comment by anarchicknight** [comment]
Are you running on the simulator? The simulator does not support this - it needs to be run on an actual device.

From memory I think this is noted in the Readme but maybe it is not clear enough right now

**Comment by anarchicknight** [comment]
closing issue - reopen if it was not due to running on the simulator
