### ISSUE TITLE
Immediate phone call on Android - without prompt?

### ISSUE THREAD

**Issue by nyariati** [anarchicknight/react-native-communications#64]
Hey there!

Is there a way to dial the number immediately? If I have more than 1 application which can dial numbers - like Cisco Jabber - then it pops up which I want to ignore and go straightforward to the Phone app.

Thanks!

**Comment by anarchicknight** [comment]
Not via this module sorry as all it is is a wrapper around Linking from react native.

It may be possible with a native code module and specifying certain values in the intent but without further digging I can't say for sure.

Closing this as not supported in this module sorry.
