### ISSUE TITLE
phonecall does not support hash key

### ISSUE THREAD

**Issue by jovi-wang** [anarchicknight/react-native-communications#74]
I am a user of rn-communications, my request is simple just want to include hash key # in the phone number, so user do not need to type number and hash to select.
But I pass hash in into the number string, it does not show in the dailer.
I am using react native 0.47.2, and communications 2.2.1

anyone knows how to fix this problem
much thanks

**Comment by anarchicknight** [comment]
What happens when using the Linking library from react-native to try and perform the same operation?

**Comment by jovi-wang** [comment]
use %23 instead of #
