### ISSUE TITLE
iOS sms, no new message if 'Messenges' is closed

### ISSUE THREAD

**Issue by fbacker** [anarchicknight/react-native-communications#75]
**libs:**
```js
"react": "16.0.0-alpha.12",
"react-native": "0.47.1",
"react-native-communications": "2.2.1",
```
**using:**
```js
Communications.textWithoutEncoding(null,json.DefaultMessage);
```
**using:**
```js
Platform: iOS 11.0.3
Device: iPhone 7 Plus
```
**Expected result:**
Opens the 'Messages' application and pre-populate an sms with content (no recipient).

**Do it yourself:**
1. Close the 'Messages' application
2. Goto react-native and Run the script
3. It opens 'Messages' then nothing happends
4. Back to application and run script again.
5. It opens 'Messages' and a populated sms is created

Note here that the **'Messages'** app **must be closed** before requesting. If the 'Messages' app is already opened it works directly (only steps 4. and 5.).

**Comment by anarchicknight** [comment]
Can you try just by using the react native linking library and see if the same happens. If it does you will need to open a bug report on the react native repo, all this library does is wrap the linking library.

If it is specific to this library then let me know and I will investigate

**Comment by vysotsky** [comment]
The same issue. But just tried the following code:
```
    const body = "Some body";
    const url = `sms:&body=${body}`;
    Linking.openURL(url);
```
And even this code doesn't work like expected.

**Comment by anarchicknight** [comment]
Thanks for investigating this. Closing this issue as the confirmation from above is that it is an issue with the Linking library from react native. I suggest you post an issue on their repo to see if they will do anything to resolve it.

If they do, this library will automatically inherit the fix

**Comment by vysotsky** [comment]
Actually the issues is not with the Linking library. It's a bug connected with iOS. Apple doesn't allow to pass a message body into Message app by using `sms:` scheme. Here what Apple says about this:

> The sms scheme is used to launch the Messages app. The format for URLs of this type is “sms:<phone>“, where <phone> is an optional parameter that specifies the target phone number of the SMS message. This parameter can contain the digits 0 through 9 and the plus (+), hyphen (-), and period (.) characters. **The URL string must not include any message text or other information**.

The right way of getting what we expected - to use MFMessageComposeViewController instead of `sms:` scheme.

**Comment by anarchicknight** [comment]
Good digging - thanks for the info, really useful to know.

I actually have the following repo which uses that, however I don't have the time to maintain it anymore https://github.com/anarchicknight/react-native-message-composer/blob/master/README.md
