### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by evanjmg** [anarchicknight/react-native-communications#80]
I tried to install it with react native 0.52. I linked it and everything, but react native could not resolve the module.

**Comment by udfalkso** [comment]
Just tried it with RN 0.54 and it seems to work nicely.

**Comment by FreakDroid** [comment]
I agree with @udfalkso Today I've installed this with:

react-native-cli: 2.0.1
react-native: 0.53.3

and works pretty good.

**Comment by anarchicknight** [comment]
seems to be working ok for me, and others have reported it working too.

Going to close this - feel free to open another issue if you are still having problems and I will see if we can debug it further
