### ISSUE TITLE
LinkingIOS and IntentAndroid are deprecated in favor of Linking

### ISSUE THREAD

**Issue by jimthedev** [anarchicknight/react-native-communications#9]
In React Native 0.20 I receive the following warnings.

```
Warning: "IntentAndroid.canOpenURL" is deprecated. Use the promise based "Linking.canOpenURL" instead.

Warning: "IntentAndroid.openURL" is deprecated. Use the promise based "Linking.canOpenURL" instead.
```

Looks like [IntentAndroid](https://facebook.github.io/react-native/docs/linkingios.html#content) and [LinkingIOS](https://facebook.github.io/react-native/docs/intentandroid.html#content) are both being deprecated

In favor of [Linking](https://facebook.github.io/react-native/docs/linking.html#content)

**Comment by anarchicknight** [comment]
Thanks for the heads up.

Just wondering on the best approach for this library going forward. Im thinking to push a new version which works with the new updates and point users on older versions of react-native to use an earlier release of this library in the readme.

Thoughts? Sounds like a feasible approach?

**Comment by pedro** [comment]
this sounds good to me – I'd just bump the major version (eg: 1.0.0) and refer people on older RN versions to check 0.x.

Thanks for this neat package!

**Comment by skleest** [comment]
Getting the same warning here, and my app actually stops functioning after opening the email and coming back to the app. I believe it's a promise issue. Thanks for your quick fix!

**Comment by anarchicknight** [comment]
Things have been hectic recently. Im expecting to have time to do this update within the next week.

If anyone submits a PR in the meantime I will take a look as soon as possible too

**Comment by anarchicknight** [comment]
1.0.1 has now been published using the new Linking module.

@skleest can you try running with the new version and see if you can still replicate your issue?

If you can please open a new issue and provide as many details as possible.

Closing this issue off
